### ISSUE TITLE
middle button opens file manager

### ISSUE THREAD

**Issue by kpelykh** [lentinj/tp-compact-keyboard#22] opened 2015-02-27 02:11 UTC
When I press middle button to scroll, it also open up a file manager window. Do you have idea how to suppress this behaviour?

**Comment by kpelykh** [comment] 2015-02-27 02:13
Another side effect when I press middle button is a buffer paste operation aka Ctrl+V

**Comment by lentinj** [comment] 2015-02-27 08:35
The former is a bug, fixed in Linux 3.19. See #11 

The latter is how you do paste in X11, it's not a bug. What was a bug though was there was a middle button click event before they keyboard started scroll-wheel emulation. This is fixed in 4.0

**Closed by lentinj** 2015-02-27 08:35 UTC
